CLUSTER_NAME: zoolabs-mgmt
CLUSTER_PLAN: prod
INFRASTRUCTURE_PROVIDER: aws
ENABLE_CEIP_PARTICIPATION: false
TMC_REGISTRATION_URL: "https://westtanzuseamericas.tmc.cloud.vmware.com/installer?id=44611631e6db440751266e076e81131f43005677b54ce840e4fdf6e10ef1d429&source=registration&type=tkgm"
ENABLE_AUDIT_LOGGING: false
CLUSTER_CIDR: 100.96.0.0/11
SERVICE_CIDR: 100.64.0.0/13
CONTROL_PLANE_MACHINE_TYPE: t3.large
NODE_MACHINE_TYPE: m5.large
AWS_REGION: "us-west-2"
AWS_NODE_AZ: "us-west-2a"
AWS_NODE_AZ_1: "us-west-2b"
AWS_NODE_AZ_2: "us-west-2c"
AWS_SSH_KEY_NAME: "se-cphillipson-cloudgate-aws-us-west-2"
BASTION_HOST_ENABLED: true
ENABLE_MHC: true
MHC_UNKNOWN_STATUS_TIMEOUT: 5m
MHC_FALSE_STATUS_TIMEOUT: 12m
IDENTITY_MANAGEMENT_TYPE: "none"
